//Adding Comments: Choose two of the programs you’ve written, and add at least one comment to each. If you don’t have anything specific to write because your programs are too simple at this point, just add your name and the current date at the top of each program file. Then write one sentence describing what the program does

//program 1
//my name is AYESHA
//Dated: 25-may-2024
console.log(`ayesha waseem simple program`);

//program 2
//my name is AYESHA
//Dated: 25-may-2024
console.log(2*5);