//Think of something you could store in a array. For example, you could make a list of mountains, rivers, countries, cities, languages, or anything else you’d like. Write a program that creates a list containing these items.

let chocolates : string [] = ["DAIRYMILK" , "KITKAT" , "SNICKERS" ,"PERK" ,"GALAXY"];
console.log("list of chocolates:")
chocolates.forEach(language => console.log(language));

