//Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:
//let car = 'subaru';
//console.log("Is car == 'subaru'? I predict True.")
//console.log(car == 'subaru')
//• Look closely at your results, and make sure you understand why each line evaluates to True or False.
//• Create at least 10 tests. Have at least 5 tests evaluate to True and another 5 tests evaluate to False.

let five = 5;

let ten = 10;

//TEST : 1
console.log("test:1 is equal to 5?")
console.log(five ==5);

//TEST : 2
console.log("\ntest:2 is equal to 10?");
console.log(ten ==10);

//TEST : 3
console.log("\ntest:3 is not equal to 10?");
console.log(five != ten);

//TEST : 4
console.log("\n test:4 10 is greater then 5?");
console.log(ten > 5);

//TEST: 5
console.log("\n test:5 5 is lesser then 10?");
console.log(ten > 5);

//TEST:6
console.log("\n test:6 5 is not equal to 5?");
console.log(five != 5);

//TEST:7
console.log("\n test:7 10 is not equal to 10?");
console.log(ten != 10);

//TEST:8
console.log("\n test 8 five is equal to 10?");
console.log(five == 10);

//TEST:9
console.log("\n test 9 10 is lesser then 5?");
console.log(ten < 5);

//TEST:10
console.log("\n test 10 5 is greater then 10?");
console.log(five > 10);