//Famous Quote 2: Repeat Exercise 4, but this time store the famous person’s name in a variable called famous_person. Then compose your message and store it in a new variable called message. Print your message.

var quote: string = "All our dreams can come true, if we have the courage to pursue them"
var famous_person = "Walt Disney"
var message = `${famous_person} once said , ${quote}`;
console.log(message);
